//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Senatwitter
{
    using System;
    using System.Collections.Generic;
    
    public partial class COMMITTEE
    {
        public COMMITTEE()
        {
            this.POLCOMMs = new HashSet<POLCOMM>();
        }
    
        public int CID { get; set; }
        public string CNAME { get; set; }
        public int ISTEMPORARY { get; set; }
    
        public virtual ICollection<POLCOMM> POLCOMMs { get; set; }
    }
}
