//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Senatwitter
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SenatwitterEntities1 : DbContext
    {
        public SenatwitterEntities1()
            : base("name=SenatwitterEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Admin> Admins { get; set; }
        public DbSet<COMMITTEE> COMMITTEES { get; set; }
        public DbSet<Party> Parties { get; set; }
        public DbSet<POLCOMM> POLCOMMs { get; set; }
        public DbSet<Politician> Politicians { get; set; }
        public DbSet<POLTWEET> POLTWEETS { get; set; }
        public DbSet<State> States { get; set; }
        public DbSet<STAT> STATS { get; set; }
        public DbSet<TWEET> TWEETS { get; set; }
    }
}
