//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Senatwitter
{
    using System;
    using System.Collections.Generic;
    
    public partial class Party
    {
        public Party()
        {
            this.Politicians = new HashSet<Politician>();
            this.States = new HashSet<State>();
        }
    
        public string PartyID { get; set; }
        public string PartyName { get; set; }
    
        public virtual ICollection<Politician> Politicians { get; set; }
        public virtual ICollection<State> States { get; set; }
    }
}
