//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Senatwitter
{
    using System;
    using System.Collections.Generic;
    
    public partial class POLCOMM
    {
        public int CID { get; set; }
        public int PID { get; set; }
        public int ISCHAIRMAN { get; set; }
        public int ISRANKINGMEMBER { get; set; }
        public System.DateTime STARTDATE { get; set; }
    
        public virtual COMMITTEE COMMITTEE { get; set; }
        public virtual Politician Politician { get; set; }
    }
}
