//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Senatwitter
{
    using System;
    using System.Collections.Generic;
    
    public partial class Politician
    {
        public Politician()
        {
            this.POLCOMMs = new HashSet<POLCOMM>();
            this.POLTWEETS = new HashSet<POLTWEET>();
        }
    
        public int PID { get; set; }
        public string Fname { get; set; }
        public string Lname { get; set; }
        public string PartyID { get; set; }
        public string StateID { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        public System.DateTime TermStart { get; set; }
    
        public virtual Party Party { get; set; }
        public virtual ICollection<POLCOMM> POLCOMMs { get; set; }
        public virtual ICollection<POLTWEET> POLTWEETS { get; set; }
        public virtual STAT STAT { get; set; }
        public virtual State State { get; set; }
    }
}
