//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Senatwitter
{
    using System;
    using System.Collections.Generic;
    
    public partial class TWEET
    {
        public int POLTWEETID { get; set; }
        public string TWEET1 { get; set; }
        public int ISRETWEET { get; set; }
        public int HASHASHTAG { get; set; }
    
        public virtual POLTWEET POLTWEET { get; set; }
    }
}
